import SimpleCodeToGraphPumper

/// Generates UMLGraph code and then (if possible) runs tooling to create the UML graph proper
public class UMLGraphCodeBuilder: ModelDisplay {

    private lazy var pumper: PumperMain = {
        let ret = PumperMain()
        ret.executeSetup()
        return ret
    }()

    public init(){}

    public func display(model: SystemModel) {

        var generatedCode: String = 
"""
//  Code generated by SwiftCodeHelper, by Kevin R. VanDenBreemen
"""

        model.classes.forEach { clz in 
            let generator = ClassCoder(for: clz)
            generatedCode += "\n\(generator.generateCode())"
        }

        model.interfaces.forEach{ iFce in 
            let generator = InterfaceCoder(for: iFce)
            generatedCode += "\n\(generator.generateCode())"
        }

        pumper.pumpOut(with: generatedCode)
        
    }
}