/// Generates UMLGraph code and then (if possible) runs tooling to create the UML graph proper
public class UMLGraphCodeBuilder: ModelDisplay {

    public init(){}

    public func display(model: SystemModel) {

        var generatedCode: String = 
"""
//  Code generated by SwiftCodeHelper, by Kevin R. VanDenBreemen
"""

        model.classes.forEach { clz in 
            let generator = ClassCoder(for: clz)
            generatedCode += "\n\(generator.generateCode())"
        }

        print(generatedCode)
        
    }
}